-- AMALA PYROTECH Supabase schema
create extension if not exists pgcrypto;

create table if not exists site_settings (
  id bigint primary key default 1 check (id = 1),
  company_name text not null default 'AMALA PYROTECH',
  logo_path text,
  announcement text,
  whatsapp_number text default '+919344265054',
  call_number text default '7780942656',
  instagram_link text default 'https://instagram.com/amalapyrotech',
  youtube_link text default 'https://youtube.com/@amalapyrotech',
  updated_at timestamptz not null default now()
);
insert into site_settings(id) values(1) on conflict(id) do nothing;

create table if not exists hero_banners (
  id bigint generated by default as identity primary key,
  storage_path text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists gallery_images (
  id bigint generated by default as identity primary key,
  storage_path text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  offer_percent numeric(5,2) not null default 85,
  created_at timestamptz not null default now()
);
create table if not exists products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  category_id bigint references categories(id) on delete set null,
  pack text default '1 Pkt',
  mrp numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  image_path text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists coupons (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount numeric(12,2) not null default 0,
  type text not null default 'percent',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null unique,
  district text,
  state text,
  town text,
  address text,
  pincode text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  customer_id bigint references customers(id) on delete set null,
  customer_name text not null,
  mobile text not null,
  pincode text,
  state text,
  district text,
  town text,
  address text,
  status text not null default 'pending' check(status in ('pending','confirmed','cancelled')),
  total_mrp numeric(12,2) not null default 0,
  savings numeric(12,2) not null default 0,
  net_total numeric(12,2) not null default 0,
  coupon_discount numeric(12,2) not null default 0,
  packing_charges numeric(12,2) not null default 0,
  grand_total numeric(12,2) not null default 0,
  transport text default 'To-Pay at Lorry Hub',
  invoice_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  cancelled_at timestamptz
);
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  code text not null,
  name text not null,
  pack text,
  mrp numeric(12,2) not null default 0,
  price numeric(12,2) not null default 0,
  qty integer not null check(qty > 0),
  amount numeric(12,2) not null default 0
);

create index if not exists orders_status_idx on orders(status);
create index if not exists orders_mobile_idx on orders(mobile);
create index if not exists orders_district_idx on orders(district);

-- Public catalog/settings read.
alter table site_settings enable row level security;
alter table hero_banners enable row level security;
alter table gallery_images enable row level security;
alter table categories enable row level security;
alter table products enable row level security;
alter table coupons enable row level security;
alter table customers enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

drop policy if exists site_settings_public_read on site_settings;
create policy site_settings_public_read on site_settings for select using (true);
drop policy if exists hero_public_read on hero_banners;
create policy hero_public_read on hero_banners for select using (true);
drop policy if exists gallery_public_read on gallery_images;
create policy gallery_public_read on gallery_images for select using (true);
drop policy if exists categories_public_read on categories;
create policy categories_public_read on categories for select using (true);
drop policy if exists products_public_read on products;
create policy products_public_read on products for select using (active = true);
drop policy if exists coupons_public_read on coupons;
create policy coupons_public_read on coupons for select using (active = true);

-- Checkout: anonymous users can create/update their own customer by mobile and create orders/items.
-- Admin reads/changes are restricted to authenticated users. For stronger production security, create an admin role/profile and tighten these policies.
drop policy if exists customers_insert_public on customers;
create policy customers_insert_public on customers for insert with check (true);
drop policy if exists customers_update_public on customers;
create policy customers_update_public on customers for update using (true) with check (true);
drop policy if exists orders_insert_public on orders;
create policy orders_insert_public on orders for insert with check (true);
drop policy if exists order_items_insert_public on order_items;
create policy order_items_insert_public on order_items for insert with check (true);

create policy customers_admin_read on customers for select to authenticated using (true);
create policy orders_admin_read on orders for select to authenticated using (true);
create policy orders_admin_update on orders for update to authenticated using (true) with check (true);
create policy order_items_admin_read on order_items for select to authenticated using (true);

-- Admin write policies. The admin panel should be used with a Supabase Auth user.
create policy site_settings_admin_write on site_settings for all to authenticated using (true) with check (true);
create policy hero_admin_write on hero_banners for all to authenticated using (true) with check (true);
create policy gallery_admin_write on gallery_images for all to authenticated using (true) with check (true);
create policy categories_admin_write on categories for all to authenticated using (true) with check (true);
create policy products_admin_write on products for all to authenticated using (true) with check (true);
create policy coupons_admin_write on coupons for all to authenticated using (true) with check (true);

-- Storage bucket for admin-uploaded media.
insert into storage.buckets(id,name,public) values('site-media','site-media',true) on conflict(id) do update set public=true;
drop policy if exists media_public_read on storage.objects;
create policy media_public_read on storage.objects for select using (bucket_id='site-media');
drop policy if exists media_admin_insert on storage.objects;
create policy media_admin_insert on storage.objects for insert to authenticated with check (bucket_id='site-media');
drop policy if exists media_admin_update on storage.objects;
create policy media_admin_update on storage.objects for update to authenticated using (bucket_id='site-media') with check (bucket_id='site-media');
drop policy if exists media_admin_delete on storage.objects;
create policy media_admin_delete on storage.objects for delete to authenticated using (bucket_id='site-media');

-- Secure public checkout RPCs: browser never needs SELECT access to customer/order tables.
create or replace function public.create_checkout_order(p_payload jsonb)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer_id bigint;
  v_order_pk bigint;
  v_order_id text := p_payload->>'order_id';
  v_item jsonb;
begin
  insert into customers(name,mobile,district,state,town,address,pincode,updated_at)
  values(
    coalesce(p_payload->>'name',''), regexp_replace(coalesce(p_payload->>'mobile',''),'\D','','g'),
    p_payload->>'district', p_payload->>'state', p_payload->>'town', p_payload->>'address', p_payload->>'pincode', now()
  )
  on conflict(mobile) do update set
    name=excluded.name, district=excluded.district, state=excluded.state,
    town=excluded.town, address=excluded.address, pincode=excluded.pincode, updated_at=now()
  returning id into v_customer_id;

  insert into orders(order_id,customer_id,customer_name,mobile,pincode,state,district,town,address,status,total_mrp,savings,net_total,coupon_discount,packing_charges,grand_total,transport,invoice_snapshot)
  values(v_order_id,v_customer_id,p_payload->>'name',regexp_replace(coalesce(p_payload->>'mobile',''),'\D','','g'),p_payload->>'pincode',p_payload->>'state',p_payload->>'district',p_payload->>'town',p_payload->>'address','pending',
    (p_payload->>'total_mrp')::numeric,(p_payload->>'savings')::numeric,(p_payload->>'net_total')::numeric,(p_payload->>'coupon_discount')::numeric,(p_payload->>'packing_charges')::numeric,(p_payload->>'grand_total')::numeric,coalesce(p_payload->>'transport','To-Pay at Lorry Hub'),p_payload->'invoice_snapshot')
  returning id into v_order_pk;

  for v_item in select * from jsonb_array_elements(p_payload->'items') loop
    insert into order_items(order_id,product_id,code,name,pack,mrp,price,qty,amount)
    values(v_order_pk,(v_item->>'product_id')::bigint,v_item->>'code',v_item->>'name',v_item->>'pack',(v_item->>'mrp')::numeric,(v_item->>'price')::numeric,(v_item->>'qty')::integer,(v_item->>'amount')::numeric);
  end loop;
  return v_order_id;
end;
$$;
grant execute on function public.create_checkout_order(jsonb) to anon, authenticated;

create or replace function public.track_order(p_value text)
returns table(order_id text, status text, created_at timestamptz, customer_name text)
language sql
security definer
set search_path=public
as $$
  select o.order_id,o.status,o.created_at,o.customer_name from orders o
  where lower(o.order_id)=lower(trim(p_value)) or o.mobile=regexp_replace(trim(p_value),'\D','','g')
  order by o.created_at desc limit 1;
$$;
grant execute on function public.track_order(text) to anon, authenticated;

-- ============================================================
-- SAMPLE CATALOG DATA REMOVED
-- ============================================================
-- The old sample categories/products are not part of the
-- AMALA PYROTECH original catalog.
--
-- The original 210-category/product catalog will be inserted
-- separately in the next catalog data file.
-- ============================================================

delete from products;
delete from categories;
